### ISSUE TITLE
Creation and updation of O- ids

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/Support#14]
Please take action for resetting the password of Girija O id

Please take action to create New O ids for new Joinees
1. Gayatri
2. Arunachalam
3. prabhakar
4. Ugesh
5. Umapathi

Please take action to create New ids for Me and Ganapathi already a request is pending

**Comment by astpl1998** [comment]
Also request ids for
6. Sujin
7. Basha

**Comment by srinivasanbaskaran** [comment]
Updation mail request sent to Viji mam.

New VPN ID creation details sent to Raju Sir...
