### ISSUE TITLE
GEN - SAP Server configuration for Transaction

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Support#16]
Configure the server for all the transactions in all the modules as below

1. Procurement
2. Sales & Distribution
3. Inventory Mgnt
4. CRM
5. AR
6. AP
7. FA
8. Production

Regards,
Srinivasan Baskaran

**Comment by astpl1998** [comment]
DueDate:26-05-19
Remarks:good

**Comment by raju-kurup** [comment]
Subscription closed, so closing this ticket
