### ISSUE TITLE
Boltz Presales Modelling

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/Support#2]
Project Management configuration for Real Estate Industry

**Comment by astpl1998** [comment]
Demo on 08-02-2019

**Comment by srinivasanbaskaran** [comment]
Data Modeling Sheet for BOLTZ Engineering Private Limited
[Data Modeling Sheet New .xlsx](https://github.com/astpl1998/Support/files/2854258/Data.Modeling.Sheet.New.xlsx)

**Comment by srinivasanbaskaran** [comment]
Presentation Completed. 

[Uploading Boltz Engg Pvt Ltd - ECOS-V1.0.pptx…]()
[Uploading Data Modeling Sheet New .xlsx…]()

**Comment by srinivasanbaskaran** [comment]
[Boltz Engg Pvt Ltd - ECOS-V0.0.pptx](https://github.com/astpl1998/Support/files/2878632/Boltz.Engg.Pvt.Ltd.-.ECOS-V0.0.pptx)
