### ISSUE TITLE
Demo Script PPT for Byd

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/Support#3]
Provide the above PPT for Demo on 04-02-2019

**Comment by girija-s** [comment]
https://help.sap.com/viewer/2754875d2d2a403f95e58a41a9c7d6de/1811/en-US/2bb77642722d10149f6796a86c3666f1.html

**Comment by girija-s** [comment]
Sir Link Pasted in GITHUB. This ticket can now be closed.

**Comment by girija-s** [comment]
Link Attached
