### ISSUE TITLE
Byd Training

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/Support#4]
Girija / Srini - Please initiate training closure - Submit all the required docs to Nirosha

**Comment by girija-s** [comment]
[SAP BYD Questions.docx](https://github.com/astpl1998/Support/files/2855395/SAP.BYD.Questions.docx)

**Comment by srinivasanbaskaran** [comment]
Supply Chain Module Question paper
[Answer Key.docx](https://github.com/astpl1998/Support/files/2856482/Answer.Key.docx)
[BYD003- Question Paper.docx](https://github.com/astpl1998/Support/files/2856483/BYD003-.Question.Paper.docx)

**Comment by srinivasanbaskaran** [comment]
Test completed
