### ISSUE TITLE
TRN - ERP Training to be given for Yugesh

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Support#5]
ERP Training to be given for Yugesh and attach the planning sheet.

**Comment by srinivasanbaskaran** [comment]
@Prabakaran92 … Kindly give daily exercise to both Umapathi & Ugesh Kumar...

**Comment by Prabakaran92** [comment]
Inventory and masters completed

**Comment by Prabakaran92** [comment]
Normal purchase flow
Blanket purchase flow
Capital purchase flow
Import purchase flow
Dropship purchase flow
Subcontracting purchase flow
and GR Account postings  Training completed

**Comment by Prabakaran92** [comment]
Normal sales and shipping flow completed

**Comment by Prabakaran92** [comment]
Export sale completed
ARD creation completed
Chart of account in progress 
Inventory adjustment 
physical inventory

**Comment by Prabakaran92** [comment]
Payable management,
receivable management ,
completed

**Comment by srinivasanbaskaran** [comment]
Trainning completed
