### ISSUE TITLE
TRN - ERP Training to be given to Umapathy

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Support#6]
ERP Training to Umapathy and planning sheet to be attached.

**Comment by srinivasanbaskaran** [comment]
Training has been started...

**Comment by srinivasanbaskaran** [comment]
@Prabakaran92 .. Kindly give daily exercise to both Umapathi & Ugesh Kumar...

**Comment by Prabakaran92** [comment]
Inventry and masters completed

**Comment by Prabakaran92** [comment]
Normal purchase flow
Blanket purchase flow
Capital purchase flow
Import purchase flow
Dropship purchase flow
Subcontracting purchase flow
and GR Account postings  Training completed

**Comment by Prabakaran92** [comment]
Normal sales and shipping flow completed

**Comment by Prabakaran92** [comment]
Export sale completed
ARD creation completed
Chart of account in progress 
Inventory adjustment 
physical inventory

**Comment by Prabakaran92** [comment]
Umapathi left from the Company
