### ISSUE TITLE
ISS - Follow Partnersandbox server setup from Ramco

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Support#7]
Follow for the setup of partnersandbox server with reports.

**Comment by astpl1998** [comment]
@ Srini as discussed send a mail trail reminding all pending points

**Comment by srinivasanbaskaran** [comment]
Sir, Mail has been sent to Sri Saravanakumar..

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

All the reports are unable to print. System shows error... 

![image](https://user-images.githubusercontent.com/46194039/57969429-6d74c280-7994-11e9-81f4-23fb78ed1bcb.png)

**Comment by srinivasanbaskaran** [comment]
Sir,

Monday Need to speak with Sri / Lakshmi  regarding this.. 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Issue resolved, so closing this ticket
