### ISSUE TITLE
IMP-Configuration of SAP BYD new server

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Support#8]
Configuration of SAP BYD new server

**Comment by srinivasanbaskaran** [comment]
New SAP tenant configured.

Production module needs to be configured.

Configured modules are,

1. Inventory
2. Purchase 
3. Sales
4. Service
5. Finance ( AR & AP )
6. Fixed Asset 
7. Employee
8. Tax Arrangements

**Comment by srinivasanbaskaran** [comment]
Production Module is only to be configured.

Due to this, Configuration is in In-Progress

**Comment by raju-kurup** [comment]
Subscription closed, so closing this ticket
