### ISSUE TITLE
Demo preparation for Swathi Engineering

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Support#9]
Prepare the product demo for Swathi Engineering.  Details of the customer is attached and website address is also mentioned.

http://www.swathiengineering.com/
[Requirement-Swathi Engineering.xlsx](https://github.com/astpl1998/Support/files/2859920/Requirement-Swathi.Engineering.xlsx)

**Comment by srinivasanbaskaran** [comment]
Preparation Completed.
[Swathi Engg - Data Sheet - B40052P.xlsx](https://github.com/astpl1998/Support/files/2869023/Swathi.Engg.-.Data.Sheet.-.B40052P.xlsx)
[Uploading Swathi Engg - V1.0.pptx…]()
